### ISSUE TITLE
How to load it?

### ISSUE THREAD

**Issue by ghiscoding** [justingrayston/basic-keyboard-event-polyfill#1]
Hello and thanks for the work on this.

I was trying to use your small polyfill to fix the `PhamtomJS` issue of `new MouseEvent("click") not a constructor` but I don't know how to load your polyfill. 

I tried loading it in my `karma.conf.js` file with this
```javascript
let polyfill = require('basic-keyboard-event-polyfill');
```
but then I get this
```javascript
TypeError: Cannot set property 'KeyboardEvent' of undefined
```

I'm using `Karma`, `Jasmine` and `AngularJS 1.5` if that helps

**Comment by ghiscoding** [comment]
Closing, I actually found a `Polyfill` that works for my usage (`mouseEvent not a constructor` which is actually different compare to yours). Anyhow, I found the answer on [MSDN MouseEvent docs](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent#Polyfill)

**Comment by justingrayston** [comment]
FYI, just require it in any test file you are testing MouseEvent. Also I think the [2.5-beta](https://bitbucket.org/ariya/phantomjs/downloads/) binary of PhantomJS _should_ have fixed this so it is compliant and no polyfill needed. Although I haven't had a chance to verify this yet. 🤞

**Comment by ghiscoding** [comment]
Oh thanks for the info, I really hope it's fixed. Their DOM come seems quite outdated.
